using System.Globalization;
using System.Text;
using Obsync.Shared.Models;

namespace Obsync.Shared.Scripting;

/// <summary>One documented table: its description and columns, read from the live catalog.</summary>
public sealed record DocumentationTable(
    string Schema, string Name, string? Description, IReadOnlyList<DocumentationColumn> Columns);

/// <summary>One column row of the data dictionary.</summary>
public sealed record DocumentationColumn(
    string Name, string DataType, bool IsNullable, bool IsPrimaryKey, bool IsIdentity, bool IsComputed,
    string? Default, string? Description);

/// <summary>The dictionary read result; <see cref="TotalTableCount"/> can exceed the capped list.</summary>
public sealed record DatabaseDocumentationData(IReadOnlyList<DocumentationTable> Tables, int TotalTableCount);

/// <summary>Reads the data-dictionary facts (tables, columns, MS_Description) for the docs artifact.</summary>
public interface IDatabaseDocumentationReader
{
    Task<DatabaseDocumentationData> ReadAsync(
        SqlConnectionProfile profile, string? password, string database, int maxTables, int commandTimeoutSeconds,
        int lockTimeoutSeconds = 0, CancellationToken cancellationToken = default);
}

/// <summary>
/// Builds <c>docs/README.md</c> — an object index plus a data dictionary — as deterministic,
/// timestamp-free markdown (LF line endings), so the file only changes when the schema does.
/// </summary>
public static class DatabaseDocumentationWriter
{
    public static string Build(
        string server, string database, IEnumerable<ObjectInventoryEntry> inventory, DatabaseDocumentationData data)
    {
        var entries = inventory.ToList();
        var builder = new StringBuilder();

        builder.Append("# ").Append(database).Append('\n').Append('\n');
        builder.Append("> Schema documentation generated by Obsync from `").Append(server)
            .Append("`. Regenerated automatically when the database changes — do not edit by hand.\n\n");

        AppendOverview(builder, entries);
        AppendDictionary(builder, data);

        return builder.ToString();
    }

    private static void AppendOverview(StringBuilder builder, List<ObjectInventoryEntry> entries)
    {
        builder.Append("## Overview\n\n");
        builder.Append(N(entries.Count)).Append(entries.Count == 1 ? " object is tracked.\n\n" : " objects are tracked.\n\n");
        if (entries.Count == 0)
        {
            return;
        }

        builder.Append("| Object type | Count |\n| --- | ---: |\n");
        foreach (var group in entries.GroupBy(e => e.Type)
                     .OrderByDescending(g => g.Count()).ThenBy(g => g.Key, StringComparer.Ordinal))
        {
            builder.Append("| ").Append(Humanize(group.Key)).Append(" | ").Append(N(group.Count())).Append(" |\n");
        }

        builder.Append('\n');

        builder.Append("### Objects by schema\n\n| Schema | Objects |\n| --- | ---: |\n");
        foreach (var group in entries.GroupBy(e => string.IsNullOrEmpty(e.Schema) ? "(no schema)" : e.Schema)
                     .OrderByDescending(g => g.Count()).ThenBy(g => g.Key, StringComparer.Ordinal))
        {
            builder.Append("| `").Append(group.Key).Append("` | ").Append(N(group.Count())).Append(" |\n");
        }

        builder.Append('\n');
    }

    private static void AppendDictionary(StringBuilder builder, DatabaseDocumentationData data)
    {
        builder.Append("## Data dictionary\n\n");
        if (data.Tables.Count == 0)
        {
            builder.Append("_No tables to document._\n");
            return;
        }

        if (data.TotalTableCount > data.Tables.Count)
        {
            builder.Append("> The dictionary lists the first ").Append(N(data.Tables.Count))
                .Append(" of ").Append(N(data.TotalTableCount)).Append(" tables.\n\n");
        }

        foreach (var table in data.Tables.OrderBy(t => t.Schema, StringComparer.Ordinal).ThenBy(t => t.Name, StringComparer.Ordinal))
        {
            builder.Append("### `").Append(table.Schema).Append('.').Append(table.Name).Append("`\n\n");
            if (!string.IsNullOrWhiteSpace(table.Description))
            {
                builder.Append(Cell(table.Description)).Append('\n').Append('\n');
            }

            builder.Append("| Column | Type | Nullable | Default | Key | Description |\n");
            builder.Append("| --- | --- | :-: | --- | :-: | --- |\n");
            foreach (var column in table.Columns)
            {
                builder.Append("| `").Append(column.Name).Append("` | `").Append(column.DataType).Append('`');
                if (column.IsIdentity)
                {
                    builder.Append(" identity");
                }

                if (column.IsComputed)
                {
                    builder.Append(" computed");
                }

                builder.Append(" | ").Append(column.IsNullable ? "yes" : "no");
                builder.Append(" | ").Append(string.IsNullOrEmpty(column.Default) ? "—" : $"`{Cell(column.Default)}`");
                builder.Append(" | ").Append(column.IsPrimaryKey ? "PK" : "—");
                builder.Append(" | ").Append(string.IsNullOrWhiteSpace(column.Description) ? string.Empty : Cell(column.Description!));
                builder.Append(" |\n");
            }

            builder.Append('\n');
        }
    }

    // A markdown table cell must stay on one line and must not break the column separators.
    private static string Cell(string value) =>
        value.Replace("\r", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal)
            .Replace("|", "\\|", StringComparison.Ordinal)
            .Trim();

    private static string N(int value) => value.ToString("N0", CultureInfo.InvariantCulture);

    // "StoredProcedure" -> "Stored procedure" for the type-count table.
    internal static string Humanize(string pascal)
    {
        if (pascal.Length == 0)
        {
            return pascal;
        }

        var builder = new StringBuilder(pascal.Length + 4);
        builder.Append(pascal[0]);
        for (var i = 1; i < pascal.Length; i++)
        {
            if (char.IsUpper(pascal[i]) && !char.IsUpper(pascal[i - 1]))
            {
                builder.Append(' ').Append(char.ToLowerInvariant(pascal[i]));
            }
            else
            {
                builder.Append(pascal[i]);
            }
        }

        return builder.ToString();
    }
}
