using System.Globalization;
using System.Text;
using Obsync.Shared.Models;

namespace Obsync.Shared.Scripting;

/// <summary>How urgently a security finding deserves attention.</summary>
public enum SecuritySeverity
{
    High = 0,
    Medium = 1,
    Info = 2,
}

/// <summary>One security-review finding: what was checked, what was found, and why it matters.</summary>
public sealed record SecurityFinding(SecuritySeverity Severity, string Check, string Subject, string Detail);

/// <summary>Reads the security posture checks for the review artifacts. Read-only catalog queries.</summary>
public interface ISecurityAnalysisReader
{
    /// <summary>Database-scoped checks: public/high-risk grants, guest, db_owner, orphans, TRUSTWORTHY.</summary>
    Task<IReadOnlyList<SecurityFinding>> ReadDatabaseFindingsAsync(
        SqlConnectionProfile profile, string? password, string database, int commandTimeoutSeconds,
        int lockTimeoutSeconds = 0, CancellationToken cancellationToken = default);

    /// <summary>Server-scoped checks: sysadmin membership, sa, password policy, high-risk server grants.</summary>
    Task<IReadOnlyList<SecurityFinding>> ReadServerFindingsAsync(
        SqlConnectionProfile profile, string? password, int commandTimeoutSeconds,
        int lockTimeoutSeconds = 0, CancellationToken cancellationToken = default);
}

/// <summary>
/// Builds a <c>security-review.md</c> artifact as deterministic, timestamp-free markdown so the
/// file — and therefore the git history — changes exactly when the security posture does.
/// </summary>
public static class SecurityReviewWriter
{
    public static string Build(string scope, IReadOnlyList<SecurityFinding> findings)
    {
        var builder = new StringBuilder();
        builder.Append("# Security review — ").Append(scope).Append("\n\n");
        builder.Append("> Generated by Obsync from the live catalog (read-only). Findings are heuristics that\n");
        builder.Append("> deserve review, not verdicts — regenerated on every run, so posture drift shows up\n");
        builder.Append("> in this file's git history.\n\n");

        if (findings.Count == 0)
        {
            builder.Append("**No findings.** Nothing needed review in this scope.\n");
            return builder.ToString();
        }

        var ordered = findings
            .OrderBy(f => f.Severity)
            .ThenBy(f => f.Check, StringComparer.Ordinal)
            .ThenBy(f => f.Subject, StringComparer.Ordinal)
            .ThenBy(f => f.Detail, StringComparer.Ordinal)
            .ToList();

        builder.Append(Summary(ordered)).Append("\n\n");

        foreach (var group in ordered.GroupBy(f => f.Severity))
        {
            builder.Append("## ").Append(Label(group.Key)).Append("\n\n");
            builder.Append("| Check | Subject | Detail |\n| --- | --- | --- |\n");
            foreach (var finding in group)
            {
                builder.Append("| ").Append(Cell(finding.Check))
                    .Append(" | ").Append(Cell(finding.Subject))
                    .Append(" | ").Append(Cell(finding.Detail))
                    .Append(" |\n");
            }

            builder.Append('\n');
        }

        return builder.ToString();
    }

    internal static string Summary(IReadOnlyList<SecurityFinding> findings)
    {
        var parts = new List<string>();
        Add(SecuritySeverity.High, "high");
        Add(SecuritySeverity.Medium, "medium");
        Add(SecuritySeverity.Info, "informational");
        return $"**{findings.Count.ToString("N0", CultureInfo.InvariantCulture)} " +
               $"finding{(findings.Count == 1 ? string.Empty : "s")}:** {string.Join(", ", parts)}.";

        void Add(SecuritySeverity severity, string label)
        {
            var count = findings.Count(f => f.Severity == severity);
            if (count > 0)
            {
                parts.Add($"{count.ToString("N0", CultureInfo.InvariantCulture)} {label}");
            }
        }
    }

    private static string Label(SecuritySeverity severity) => severity switch
    {
        SecuritySeverity.High => "High",
        SecuritySeverity.Medium => "Medium",
        _ => "Informational",
    };

    private static string Cell(string value) =>
        value.Replace("\r", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal)
            .Replace("|", "\\|", StringComparison.Ordinal)
            .Trim();
}
